### ISSUE TITLE
Cloudkit usage for EVCloudKitDao

### ISSUE THREAD

**Issue by yoonack** [evermeer/EVCloudKitDao#10]
I realized that there are limits for the daily transfer of the data in icloud. As for EVCloudDataObject, it contains many field, such as modify date, recordID, and so on. I am wondering what's the size of one EVCloudDataObject? Have you encountered any problem that would go over the limit of the icloud storage? 

Since in my app, it continuously retrieves certain public data whenever the view is loaded. I kind of want to know the impact of this limitation of the cloudkit.

**Comment by evermeer** [comment]
These fields are meta data fields. These fields will always be part of your CKRecord the moment you fetch it. The properties inside the EVCloudDataObject are convenience properties. This way it's easy to access all those meta data fields. There won't be additional data send or read from CloudKit than when you would have done similar operation without EVCloudKitDao.

I must admit that the free transfer limits are also a concern with me. Especially since there is no way tho see how much you have used or are using. I have an outstanding issue at Apple for this, but I'm not getting any answers. As long there is no good dashboard with this information you cannot tell how apple really calculates these numbers. Storage and transfer limits can be found here: https://developer.apple.com/icloud/documentation/cloudkit-storage/

So we have to guess... An app that uses CloudKit has a default transfer limit 250KB plus 5KB per user per day (excluding assets). In my experience (largely depends on the type of app you have) only 10% of users will keep on using your app and of those users the average usage is less than once every other day. This would mean that you can have up to 5 * 10 * 2 = 100KB of data transfer for every active user. That would be more than enough for the app that I am building. But still this is all based on assumptions.

**Comment by yoonack** [comment]
Thanks a lot for the explanation. I heard that the private DB has no limits on it. I might think about a way to migrate some part to the private DB instead of keep querying the public DB

**Comment by evermeer** [comment]
For storage private DB storage counts against the users account. So by default they could potentially store up to 5GB of data. I'm not sure about transfer limits. I have not seen any information about that.

**Comment by yoonack** [comment]
Just a quick question, I am trying to fetch a record that using NSPredicate. Do you know how to match either of two fields with a string value? My approach is: "fieldA == %@ || fieldB == %@", stringToMatch, stringToMatch.
I try to find answer online, but no luck. Sorry to bother you here.

**Comment by evermeer** [comment]
Yes, that's a bad one... I already posted a request for change with apple for that... The point is that OR queries are not supported. See the documentation at https://developer.apple.com/library/prerelease/ios/documentation/CloudKit/Reference/CKQuery_class/index.html
