### ISSUE TITLE
Difficulty getting AppMessage demo to work on device

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#20]
Hi, I'm trying to run the demo app on my iPhone 5S with iOS v9.1 and keep getting a "DENIED CLOUDKIT" state in the permission scope popup when running it. If I delete the app and remove it, I am always prompted to allow push notifications, but I never see a system prompt to allow the app access to my iCloud account.

It seems to run okay in the simulator using an iPhone 6s Plus virtual device, although the news items don't update unless I shut down and restart the app (no notification receipt and automatic updating if left on the news screen). I believe this is an issue with the simulator though. Doesn't it have problems receiving push notifications?

I did the following as instructed in order to build and run the app:
- Changed the bundle name to my expected bundle name (com.tommyb.AppMessage)
- Created a "com.tommyb.AppMessage" APNs Development iOS certificate
- Checked "key-value storage" and "CloudKit" options and used the default container after enabling iCloud capabilities
- Enabled Background modes' "Background Fetch" and "Remote notifications" capabilities
- Uncommented the createRecordTypes method and ran the app
- Commented the createRecordTypes method out again after the run once exception was thrown
- Went to my CloudKit dashboard and enabled all of the metadata indices for the created record types

When I launch the app, I get this console output:

10/26/2015 03:36:26:752 AppMessage)[209:.] EVCloudKitDao.swift(172) init():
	Container identifier = Optional("iCloud.com.tommyb.AppMessage")

10/26/2015 03:36:26:768 AppMessage)[209:.] EVCloudKitDao.swift(170) init():
	Account status = 1 (0=CouldNotDetermine/1=Available/2=Restricted/3=NoAccount)

10/26/2015 03:36:27:565 AppMessage)[209:.] EVCloudKitDao.swift(423) getUserInfo(_:errorHandler:):
	requestDiscoverabilityPermission : No permissions

2015-10-26 03:36:27.570 AppMessage[209:4657] Error: Optional(Error Domain=EVCloudKitDao Code=1 "(null)")
10/26/2015 03:36:27:572 AppMessage)[209:.] RootViewController.swift(86) getUser:
	ERROR in getUserInfo: Error Domain=EVCloudKitDao Code=1 "(null)"

10/26/2015 03:36:27:575 AppMessage)[209:.] RootViewController.swift(87) getUser:
	You have to log in to your iCloud account. Open the Settings app, Go to iCloud and sign in with your account. (It could also be that your project iCloud entitlements are wrong)

10/26/2015 03:36:27:588 AppMessage)[209:.] Helper.swift(34) showError:
	ERROR: Could not get user: The operation couldn’t be completed. (EVCloudKitDao error 1.)

I have tried deleting the app and shutting down and powering up my phone but I still see the same behavior. Any suggestions on what I can do to fix this?

**Comment by evermeer** [comment]
Are you sure that you are loged in into iCloud on your device?

You are getting 4 error messages that all originate from 1 point in the code. In the RootViewControler at line 69 there is a call to .getUserInfo which will the call the container.requestApplicationPermission which will return the 'No permissions' that you can see in your first error. This is the origin of the rest of the messages.

This should only happen when you press no on the question if you want to be discovered by other users. I have looked how to reset that setting, but I can't find it. The only workaround so far is that you change your bundle identifier so that it's like a new app that will request the access again.

I think i can get the user id without calling the requestApplicationPermission first. I will try that now.

**Comment by evermeer** [comment]
I was able to skip the requestApplicationPermission when getting the userId. I pushed that as version 2.10.0 But then you would still not be able to see any contacts since you denied discoverability. I'm still looking for a way how that setting could be changed.

**Comment by evermeer** [comment]
OK, I found the following information about resetting discoverability.

Open the settings app, iCloud, iCloud Drive, look me up by email.

One disadvantage: You will only see the apps where you can change the setting for a production environment. Since you use the app in development, you cannot reset the setting

This is a copy of the info that i found:
The "Look Me Up By Email" settings currently only show your preferences in the production environment. If your app is running in the development environment there's no way to reset those settings at the moment. You're correct that the setting is stored on the server.

This is a known bug. Until it gets fixed the work around is to test this feature while your app is deployed for production. You can create a second container to use for testing this if you want to avoid testing in your shipping app's production container.

**Comment by tbaggett** [comment]
Wow, thanks so much for going above and beyond on tracking down the problem source! I don't recall clicking anything to deny the discoverability permission but that must've been what happened. I did try logging into iCloud and looking at the apps that were given permission to see if I could reset it, but I didn't think about apps in the development environment not showing up. I will create another bug report issue.

Do you have any sort of tip jar for your open source components? I definitely owe you a round and would be happy to cover it. Thanks again for your help on both this and the tvOS support.

**Comment by evermeer** [comment]
Your welcome. You actually also help me finding bugs. I am using EVCloudKitDao in my own app that I hope to release in a couple of months. I have a lot of fun creating all the libraries on GitHub. I found out that it's a great way to improve the code that you are creating. It's now some sort of a sport for me to keep the issue count to 0 on all my libraries.
