### ISSUE TITLE
New tvOS and/or Xcode Betas (released 11/10/15) breaks EVCloudKitDao v2.11.0

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#23]
Hello again, sorry to always be the bearer of bad news! I updated to the new beta of Xcode (7.2 Beta 3) and tvOS (9.1 Beta 2), both of which were released today, and found that I am unable to build the project due to the following. Hopefully this requires nothing more than a rebuild with updated libs or something similar. It could also be a bug in the beta releases.

EVCloudKitDao.swift -
    'shouldSendContentAvailable' is unavailable
        'shouldSendContentAvailable' has been explicitly marked unavailable here

The attempt to set the property value occurs in the "subscribe" method, line 636:

        let createSubscription = { () -> () in
            let subscription = CKSubscription(recordType: recordType, predicate: predicate, subscriptionID:key, options: [.FiresOnRecordCreation, .FiresOnRecordUpdate, .FiresOnRecordDeletion])
            subscription.notificationInfo = CKNotificationInfo()

            subscription.notificationInfo!.shouldSendContentAvailable = true

            if let configure = configureNotificationInfo {
                configure(notificationInfo: subscription.notificationInfo!)
            }
            self.database.saveSubscription(subscription, completionHandler: { savedSubscription, error in
                self.handleCallback(error, errorHandler: errorHandler, completionHandler: {
                    EVLog("Subscription created for key \(key)")
                })
            })

**Comment by evermeer** [comment]
Thanks for reporting this. An issue that is reported is always better than an issue that's not reported.

Strange... According to the prerelease documentation it should still be available... 
https://developer.apple.com/library/prerelease/ios/documentation/CloudKit/Reference/CKNotificationInfo_class/#//apple_ref/occ/instp/CKNotificationInfo/shouldSendContentAvailable 

I'm now downloading the beta... will test this later today.

**Comment by evermeer** [comment]
Ha! when switching fro iOS to OS X to AppleTV you can see that the CKNotificationInfo object itself is different. For AppleTV the shouldsendContentAvailable property is just removed from the object. I can't find any information about why this was done and how this influences the behavior of notifications. 

Since you won't be able to receive actual push notifications on AppleTV and it's only used for synchronizing data where the data has to be handled by the app itself, I assume (guess) the default behavior on AppleTV is like the property is set to true. 

It looks like there is no alternative functionality available for this property. The only available option I have is skipping that line for AppleTV. I just added conditional compilation for that line and pushed this as version 2.11.1 to GitHub.

**Comment by tbaggett** [comment]
Great, thanks for taking care of that. I (heart) undocumented changes. Not.
