### ISSUE TITLE
Problem retrieving data after moving data classes to framework

### ISSUE THREAD

**Issue by tbaggett** [evermeer/EVCloudKitDao#36]
Hi Edwin, 

I REALLY hope you will have some immediate ideas on an issue I ran into today. 

First, a little background info: tvOS apps have what is called a "Top Shelf" extension. You implement the extension when you want to provide dynamic content at the top of the main Apple TV interface if your app is moved to the top row and selected. See https://developer.apple.com/tvos/human-interface-guidelines/#top-shelf for more info.

I need to access some of my iCloud data in the extension code, which requires me moving some of my support code and your EVCloudKitDao pod into a framework that can be accessible by both my app and the extension. I took it a step further, creating both a reusable "CommonData" framework, which contains my observable classes and EVCloudKitDao, and an app-specific data framework, which contains my app-specific EVCloudKitDataObject-derived classes and models.

Everything compiles and runs successfully, but no data is ever retrieved. IOW, all the EVCloudData.privateDB.data[""] members are empty arrays. I also don't see any errors indicated in the console output. 

FYI, I made a copy of the whole project to make these changes in. If I run the original unchanged project, everything works fine, even after updating to the latest pod versions. I can also still see all the data in the iCloud Dashboard.

I realize this may not be a problem with your project at all, but I am not very familiar with how your EVReflection library that EVCloudKitDao depends on works. Is it possible that there is a reflection issue being caused by EVCloudKitDao being in one framework and the EVCloudKitDataObject-derived classes being in another framework?

Any possible directions to look to solve this is GREATLY appreciated. I'm stumped at the moment. Thanks!

**Comment by evermeer** [comment]
I think this could be because of an issue with EVReflection. When instantiating a class, it needs to create the complete identifier that includes the framework/application name. It will usually take the active application. I had that problem before. Because of that I added code to force a specific framework. You could call:
EVReflection.setBundleIdentifier(aClassThatIsInYourBundle)
Could you try this?
There still is one disadvantage. Currently it's not possible to use 2 different bundles at the same time. If you have multiple bundles you have to make sure you use one at a time and set this whenever you change bundle.

Restructuring this so that this problem is gone was on my whishlist. I will move the priority up. I think I can start on it next week.

**Comment by evermeer** [comment]
O, I think there is one other workaround. You could place all your data classes inside an other class. Swift will then create full class descriptions instead of clean names. The disadvantage is that your recordTypes would also be named after that complete description.

**Comment by tbaggett** [comment]
Awesome, adding the EVReflection.setBundleIdentifier call did the trick! All of my EVCloudKitDataObject-derived classes are defined in a single framework, so I should be good to go. Thanks again for your help and a great library!
