### ISSUE TITLE
How to modify existing record in the iCloud?

### ISSUE THREAD

**Issue by yoonack** [evermeer/EVCloudKitDao#5]
I know that the saveItem is used to save new record. Does it apply to modifying the existing record? or should use another API to do so? Thanks for the great library btw

**Comment by evermeer** [comment]
With EVCloudKitDao you just first have to read an object, change some properties and then call the saveItem to save the update. CloudKit itself needs a CKRecord with the right metadata fields for this to work. EVCloudKitDao makes sure these fields are set correctly.

**Comment by yoonack** [comment]
So the saveItem would modify existing record instead of creating a new one right? I really appreciate your great library, that saves me a lot of trouble

**Comment by evermeer** [comment]
yes, that's right, as long as it's an object that has been read from CloudKit. Because reading an object will populate all the metadata fields. See the EVCloudKitDataObject for an overview of all the properties that you get. Great to hear that you appreciate this library. If you have any more questions, then don't hesitate to ask. Also any feedback about missing functionality is welcome.
