### ISSUE TITLE
discoverUserInfo not work

### ISSUE THREAD

**Issue by misuqian** [evermeer/EVCloudKitDao#57]
discoverUserInfo spent a long long long time and nothing happen
how can i get the current user id without using discoverUserInfo
`HUDshow(self.view)

                let sema = dispatch_semaphore_create(0)
                EVCloudKitDao.publicDB.discoverUserInfo({
                        print("user \($0)")
                    HUDhide(self.view)
                    dispatch_semaphore_signal(sema);
                    }, errorHandler: {
                        print("error \($0)")
                        HUDhide(self.view)
                        dispatch_semaphore_signal(sema);
                })
                HUDhide(self.view)
                dispatch_semaphore_wait(sema, DISPATCH_TIME_FOREVER);`

**Comment by misuqian** [comment]
OK . CKContainer.defaultContainer().fetchUserRecordIDWithCompletionHandler can get the user record but can't get information dic from discoverUserInfoWithUserRecordID

**Comment by evermeer** [comment]
The EVCloudKitDao discoverUserInfo function will execute 2 CloudKit functions. It will first execute the fetchUserRecordIDWithCompletionHandler and with the returned recordID it will execute a discoverUserInfoWithUserRecordID.

Do I understand correctly that the first step fetchUserRecordIDWithCompletionHandler will execute without problems. And you don't get an error message (your errorHandler is not called)?
Then when the 2nd step discoverUserInfoWithUserRecordID is executed it will take a long time without returning any data or error?
When you set a breakpoint on both your print functions, will none of them be triggered at all?

You do have to be aware that all functions are asynchronous. In EVCloudKitDao the callbacks will all be on a background thread. When updating your UI you have to call the code on the main queue yourself. For the EVCloudData class i am executing all callback function on the main queue.  This is different because EVCloudKitDao is meant to be used on a lower level than EVCloudData.

**Comment by misuqian** [comment]
Thank you for your reply
Yes, the 2nd step take a long time without returning any data and i don't know why
so i give up the information of user and use the record id only
