### ISSUE TITLE
Optional("<CKError 0x16d0f060: \"Server Rejected Request\" (15/2032); server message = \"subscription is duplicate of \'XXXXXXX-495E-456A-9B83-14FE13FC7592\'\"; uuid = XXXXXXX-32F1-4525-8C14-472EA51A83CD 

### ISSUE THREAD

**Issue by yoonack** [evermeer/EVCloudKitDao#6]
I keep getting this error everytime I tried to use the EVCloudData.privateDB.connect method. Do you have any idea what might cause that?
Thanks

**Comment by evermeer** [comment]
I will do some tests for this. It looks like it's possible for a new subscription to be created before the old one is deleted. I will keep you posted...

**Comment by evermeer** [comment]
I just pushed version 2.1.0 to githug where the creation of a subscription will start after the removal if it already existed. Could you please try this version out to see if this solved your issue?

**Comment by yoonack** [comment]
EVCloudKitDao.swift(204) handleCallback(_:errorHandler:completionHandler:):
	Error: Optional(15) = Optional("<CKError 0x15edcfe0: \"Server Rejected Request\" (15/2032); server message = \"subscription is duplicate of \'XXXXXXX-2ABE-4A43-85C1-FEBE3E525627\'\"; uuid = XXXXXXXX-6CD0-4FBD-A96D-E175E1880096; container ID = \"XXXXXXXXXXXXXXXXXXX\">") 
Optional([errorKey: ck1utiaf, NSDebugDescription: CKInternalErrorDomain: 2032, ErrorDescription: subscription is duplicate of 'XXXXXXX-2ABE-4A43-85C1-FEBE3E525627', RequestUUID: XXXXXXX-6CD0-4FBD-A96D-E175E1880096, ContainerID: XXXXXXX,
 NSUnderlyingError: <CKError 0x15ef6a90: "Unknown Error" (2032); server message = "subscription is duplicate of 'XXXXXXX-2ABE-4A43-85C1-FEBE3E525627'"; uuid = XXXXXXX-6CD0-4FBD-A96D-E175E1880096; container ID = "XXXXXXX">, NSLocalizedDescription: Error saving record subscription with id XXXXXXX-E93A-4117-A013-2F577D107D77 to server: subscription is duplicate of 'XXXXXXX-2ABE-4A43-85C1-FEBE3E525627'])

I still get this error everytime I called EVCloudData.privateDB.connect method. I checked my subscription type in the icloud storage, there is subscription with such ID. I am not sure what went wrong.

**Comment by yoonack** [comment]
EVCloudData.privateDB.connect(Message(),
            predicate: NSPredicate(value: true),
            filterId: dataId,
            configureNotificationInfo: { notificationInfo in },

**Comment by evermeer** [comment]
Since it's not possible to update a subscription, I always delete the current subscription and then create a new one. This is to make sure that the subscription is exactly the same as what is specified in the .connect. It looks like that in your case the old subscription does not get deleted before the new one is created. I will do some more tests this evening.

**Comment by evermeer** [comment]
Do you still have difficulties with this? I'm not seeing this behavior both in the demo app as in my own app. If you still have this problem, then it would be nice if you have some pointers or code snippets for me so that I could try to reproduce this issue.

**Comment by yoonack** [comment]
I think sometimes yes. I didn't change anything, I just use connect method, and this message will pop up later. However, if I remove the subscription, this message will not show up. I have no idea what went wrong

**Comment by evermeer** [comment]
OK, I think I now have a clue what could happen. If you log in with the same iCloud ID on multiple devices (or device and simulator) then it could happen than on device A a subscription is created and it's id is stored in the NSUserDefaults. Then you start the app on device B and it does not find the ID in the NSUserDefaults and therefore won't unsubscribe. Instead it will create the subscription. Since it's for the same NSPredicate you will get this error. 

I think I know how to solve this. It's posible to give a subscription it's own ID. That way i will be able to delete it. I think I will have this fix ready this saturday. I will keep you posted.

**Comment by yoonack** [comment]
Oh Nice, yeah, I used both real iphone and simulator to test the app. I guess this could be the cause. Great to hear that it gonna get fixed.

**Comment by evermeer** [comment]
Solving this was easier than expected. I just pushed version 2.2.0 to GitHub. 
I am now using the subscriptionId to see if it already exists in CloudKit and If it does, it will be removed and recreated.

**Comment by yoonack** [comment]
I wonder why you need to keep removing subscription and resubscribing. Why not just keep the subscription there and do not resubscribe if it already exist?

**Comment by evermeer** [comment]
that originated from the beginning of using CloudKit in my app. I frequently changed the predicate for a subscription. Then I needed to delete and create it again. Now that I am already reading the subscription first to see if it's there, I might be able to check if the predicate has changed. I will look into that now. If that does not work, then I might make the recreation optional so that you have control over it.

**Comment by evermeer** [comment]
I just pushed version 2.3.0 to GitHub. The logic of creating a subscription is now:
- Do a read to see if a subscription exists.
- If it does not exists, then just create it.
- If it does exist, then compare the read subscription predicate with the new predicate.
- If it's the same, then do nothing
- if it's different, then delete the old subscription and create the new subscription.
I think this is the most optimal way of handling subscriptions. 

You can now only get a subscription duplicate error if you create 2 identical subscriptions with 2 different subscriptionID's
