### ISSUE TITLE
how to get next 100 results for query?

### ISSUE THREAD

**Issue by foolbear** [evermeer/EVCloudKitDao#93]

**Comment by evermeer** [comment]
When using the .connect in the EVCloudKitData object then in the completionHandler callback you would handle this like this:
`return status == CompletionStatus.partialResult && results.count < 200`
Which means, if there is more data (.partialResult) and we still don't have enough records < 200 then automatically continue reading more data. So fetching the next 100 will go automatically.

The same logic goes for the .query functions in EVCloudKitDao object. you will get an isFinished value and have to return true if you want to continue reeding

by the way. the 100 is not a fixed amount. Depending on the load CloudKit could give less records in return.

**Comment by foolbear** [comment]
That's not what I need.
I want query 10 items, then click "more" for next 10 items, and go on...

**Comment by evermeer** [comment]
That would be a little harder to do... You can't do it using the EVCloudKitData .connect function because that's executed on the main thread. You would need to use the .query functions in EVCloudKitDao. You also need some sort of hack to do it. You would need to use a semaphore.

In the completionHandler, right before returning true to give a signal to continue reading you have to wait for a semaphore. On the click "more" you then have to trigger the semaphore so that the code will continue.

So you would end up with something like:

```
let sema = DispatchSemaphore(value: 0)

func doQuery() {
   .query( ...
        completionHandler: {
            ...handle data
            let _ = sema.wait(timeout: DispatchTime.distantFuture);
            return true
       })
}

func continueReading() {
      sema.signal();
}
```

**Comment by foolbear** [comment]
Does CloudKit support such an operation?

**Comment by evermeer** [comment]
Yes, But in EVCloudKit I decided to handle it by handling a true or false in the completionHandler. If you look at the code of the .query you will see that it will save the cursor (line 332) and based on the return value of the completionHandler it will execute a new query that starts at that cursor.

Since I handle it directly you have to add wait mechanism (the semaphore) before you continue with the next read.

**Comment by foolbear** [comment]
Roger that, thanks .
